@BASE_URL = http://localhost:3333

POST {{BASE_URL}}/subscriptions
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@gmail.com",
}

###
GET {{BASE_URL}}/invites/<:id>

###
GET {{BASE_URL}}/subscribers/<:id>/ranking/clicks

###
GET {{BASE_URL}}/subscribers/<:id>/ranking/count

###
GET {{BASE_URL}}/subscribers/<:id>/ranking/position

###
GET {{BASE_URL}}/ranking